services:
  minio:
    image: quay.io/minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: "root"
      MINIO_ROOT_PASSWORD: "rootroot"
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
  mc:
    image: quay.io/minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      until (mc alias set myminio http://minio:9000 root rootroot);
      do echo 'Waiting for MinIO to be ready...'; sleep 3; done;
      mc mb myminio/state;
      echo 'Buckets created successfully';
      "

volumes:
  minio_data:
